### ISSUE TITLE
A couple of website requests...

### ISSUE THREAD

**Issue by andrewrushby** [Knowinnovation/Nexss-#5]
Hi Andy, Julia! 

Happy New Year! And apologies for the radio silence on my end but there has been little movement on the NExSS front over the holidays; the first Jedi meeting I'd attended in some time was last week. We did come up with a couple of requests however.

Dawn would like [the new poster ](https://drive.google.com/open?id=0B0pIA0zyas_penp6eWg5WkdDaXM) for our upcoming conference on the site ASAP, and in a nice prominent place... I was thinking I'd write a short news post about it (no help needed on that end), and that the poster itself could be embedded in the sidebar near the events section? It should also be found somewhere on the actual [conference webpage](https://nexss.info/community/workshops/habitable-worlds-2017) too please.

Natalie would like a 'portal' for all the JWST Early Release stuff she's working on with the ERS working group, which is going quite well apparently and has over 80 members. This can be a public-facing page or set of pages (no login required) to include announcements, document hosting and potentially videos. I'd suggest this be listed under the 'Community' tab on the header bar?

Furthermore, we're getting a couple of annual reviews from some of our teams which we'd like on the website, but on the members-only side. I haven't got all of them yet, but when I do I'll pop them in a drive folder and send over a link.

Thanks, 
Andrew

**Comment by julia-figs** [comment]
Hi Andrew, I've updated the front page and conference page to include the poster for the event. Please let me know if that is what you had in mind.

It won't be a problem to create a new portal under the Community tab. I would need to know the proposed title for the page. Are there documents and announcements that you have ready to be posted? And, would you like a preview of the page on our dev site prior to setting it up on the live website?

All the best,
Julia

**Comment by andrewrushby** [comment]
Julia,

Thanks for that, it all looks good to me. However, is there a way of setting the poster image to autoscale to the width of the sidebar? Ideally, it'd be nice for this image to make use of the full width of the sidebar (while maintaining aspect ratio).

I think the title for this new page could just be 'Annual Reports'. There are some documents ready to be uploaded [in this folder](https://drive.google.com/drive/folders/0B0pIA0zyas_pa2Z2MGo1ZGRWLWs?usp=sharing). A preview would be handy; I can run it by the others on Friday for approval in that case.

Thanks!
Andrew

**Comment by julia-figs** [comment]
Good point, Andrew. I've set the poster to autoscale in the sidebar depending on browser width.

Is the Annual Reports page the same menu item that Tony was talking about in his email? If so, he requested the page go under the For Members menu, due to the members-only privacy level. However, if the goal is to have it under the Community tab, I can still make it accessible only to Members, PIs, and Management Team without a problem. For now, I'm discussing the best site component to use for document uploads with some of our tech people. Unless, of course, you prefer this layout for showing documents, in which case I can move forward with that: https://dev.nexss.info/nexss-proxima-portal

Could you please give me more information (specifically the proposed title for the page, and any documents, announcements, and/or videos that you have ready to be posted) on the following?
_Natalie would like a 'portal' for all the JWST Early Release stuff she's working on with the ERS working group, which is going quite well apparently and has over 80 members. This can be a public-facing page or set of pages (no login required) to include announcements, document hosting and potentially videos. I'd suggest this be listed under the 'Community' tab on the header bar?_

Thanks,
Julia

**Comment by andrewrushby** [comment]
Hi Julia,

Yes, that's the same issue Tony mentioned. I think this is something we'll probably have to chat about tomorrow, but I think it's best to follow Tony's direction for now and prepare for it to exist under the For Members menu. Links to the documents would be adequate and functional; I don't think we'd need icons etc. Let us know what you decide regarding document/file hosting.

Oh, okay sorry! This page will be a front-end for Natalie's James Webb Space Telescope Early Release Science Working Group, which is a bit of a mouthful admittedly. 'JWST ERS Working Group' would be fine as a title I think.  Personally, I think the Promixa Portal format would work for this page, especially as it has the 'discussion' toolbox. I'll meet with Natalie later and get a better idea of exactly what files she'd like to host on this page. I'd imagine we'll have a short intro blurb at the top (tbd), a few links to files they're working on, important papers etc., the discussion box, and maybe a video or two on the sidebar. 'JWST ERS' as a search term on twitter seems quite well used so it might be an idea to have that featured on the side too to keep folks up to date with what's being said on social media. Once I have this confirmed I'll pass on more details. 

Thanks,
Andrew

**Comment by julia-figs** [comment]
Thanks Andrew,

Until we get the local document hosting capability sorted, is it okay to link them directly to the files you shared with me in Google Docs? If not, I'm happy to transfer the finished documents into a separate Google Drive folder within our company NExSS folder.

Either way, you can find the test page at https://dev.nexss.info/for-members/annual-reports. Please note that you will have to be logged in to see it. The rest of the menu items may not match up with the live site, because this is simply a preview of that page.

In regards to the JWST ERS menu, I'll await further information from you and Natalie.

Best,
Julia

**Comment by andrewrushby** [comment]
Hi Julia,

So I've just had a meeting with Natalie and we came to the following conclusions:

- We're going to have a chat about the Annual Reports page tomorrow at our team meeting. The format of the page looks good, but can we have the PI's name, alongside their NExSS group name (already in place)? I think we'd prefer to have the files hosted locally as opposed to linking to a Drive folder (which, by HQ's directives we shouldn't really even be using apparently...we might have to address this at some points soon, but that's for another time) for security purposes.

- Natalie has taken the initiative to set up an ERS group where she can post files and updates to lighten your workload and ensure that she can make changes without having to go through a third party each time. However, she would appreciate it if this group could be accessed from the Community menu, under a new 'Public Groups' tab (she doesn't need this to be a Members-Only group - I think I configured it this way when I set it up).

- We stumbled across the fact that the Steering Committee >> NExSS Activites page does not exist anymore... (https://nexss.info/groups/steeringgroup/wiki/IdeasforNExSSActivities)

- I need to send you some more papers to add to our Proxima Portal. I will try and do this by next week. 

Thanks!
Andrew

**Comment by julia-figs** [comment]
Hi Andrew,

- I've added PIs to the Annual Reports page. Let me know if that format works for your team. I will also try to expedite the discussion around file hosting so we can host the NExSS files in a secure and site-local place that is not Google Drive.
- Would you like the ERS group to be available on the Community menu now, or when it's finalized? If there's anything I can do to help set up the group, please let me know.
- I've updated the Steering Committee page with the proper information. I'm not sure where that wiki page went! Something I've noticed, though, is that the same information is both under the Steering Committee menu (https://nexss.info/groups/steeringgroup/wiki/IdeasforNExSSActivities) and the For Members menu (https://nexss.info/wiki/IdeasforNExSSActivities). The former is within a group wiki, the latter is a site-wide wiki. Does the team want both of those to be featured on the main menu?

**Comment by julia-figs** [comment]
Hi Andrew,

Per today's Jedi meeting, I can move the Annual Reports page to the live site. We don't yet have a permanent fix for file hosting, but temporarily I can upload these files directly to the backend of the site and link from there. Once our fix takes place, I can move them over to a more accessible collection. Would you like me to proceed, or wait until we have our permanent solution?

Julia
