### ISSUE TITLE
EPRV Conference for the website

### ISSUE THREAD

**Issue by andrewrushby** [Knowinnovation/Nexss-#7]
Hi Julia, Andy

I hope you're both well! Just a brief request from Friday's meeting that I've only just remembered to raise: we'd like to advertize the upcoming [EPRV workshop](http://exoplanets.psu.edu/events-page/meetings/eprv3/) that's being held at Penn State as it's partially sponsored by NExSS and it features many of our folks. I will write a short news item about it later today, but perhaps we could get the poster up on the sidebar? It might be an idea to replace the outdated Exoplanetary Space Weather workshop link on the banner with a link to this workshop instead too.

Thanks,
Andrew

**Comment by julia-figs** [comment]
Hi Andrew,

Sorry I missed Friday's call. I've swapped out the Exoplanetary Space Weather workshop banner for the upcoming EPRV workshop. I've also added the poster to the sidebar. It's currently before the Habitable Worlds 2017 poster, since this event is sooner, but would you prefer it to follow HabWorlds since that one is **entirely** NExSS sponsored and organized?

**Comment by andrewrushby** [comment]
Julia,

No problem, and thank you for swapping out those out. I think we should keep our Habitable Worlds poster at the top, especially as we're ramping up now and pre-registration is now available.

Thanks,
Andrew

**Comment by julia-figs** [comment]
Thanks Andrew, all set!
